// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.ts";
import * as $pmims_api_middleware from "./routes/pmims_api/_middleware.ts";
import * as $pmims_api_a_sse from "./routes/pmims_api/a_sse.ts";
import * as $pmims_api_ci from "./routes/pmims_api/ci.ts";
import * as $pmims_api_commit from "./routes/pmims_api/commit.ts";
import * as $pmims_api_conf_get from "./routes/pmims_api/conf_get.ts";
import * as $pmims_api_conf_set from "./routes/pmims_api/conf_set.ts";
import * as $pmims_api_db from "./routes/pmims_api/db.ts";
import * as $pmims_api_f from "./routes/pmims_api/f.ts";
import * as $pmims_api_ibus_sse from "./routes/pmims_api/ibus_sse.ts";
import * as $pmims_api_li from "./routes/pmims_api/li.ts";
import * as $pmims_api_m from "./routes/pmims_api/m.ts";
import * as $pmims_api_p2c from "./routes/pmims_api/p2c.ts";
import * as $pmims_api_pin_yin from "./routes/pmims_api/pin_yin.ts";
import * as $pmims_api_user_gc from "./routes/pmims_api/user_gc.ts";
import * as $pmims_api_user_rm from "./routes/pmims_api/user_rm.ts";
import * as $pmims_api_version from "./routes/pmims_api/version.ts";
import * as $time from "./routes/time.ts";
import * as $version from "./routes/version.ts";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.ts": $index,
    "./routes/pmims_api/_middleware.ts": $pmims_api_middleware,
    "./routes/pmims_api/a_sse.ts": $pmims_api_a_sse,
    "./routes/pmims_api/ci.ts": $pmims_api_ci,
    "./routes/pmims_api/commit.ts": $pmims_api_commit,
    "./routes/pmims_api/conf_get.ts": $pmims_api_conf_get,
    "./routes/pmims_api/conf_set.ts": $pmims_api_conf_set,
    "./routes/pmims_api/db.ts": $pmims_api_db,
    "./routes/pmims_api/f.ts": $pmims_api_f,
    "./routes/pmims_api/ibus_sse.ts": $pmims_api_ibus_sse,
    "./routes/pmims_api/li.ts": $pmims_api_li,
    "./routes/pmims_api/m.ts": $pmims_api_m,
    "./routes/pmims_api/p2c.ts": $pmims_api_p2c,
    "./routes/pmims_api/pin_yin.ts": $pmims_api_pin_yin,
    "./routes/pmims_api/user_gc.ts": $pmims_api_user_gc,
    "./routes/pmims_api/user_rm.ts": $pmims_api_user_rm,
    "./routes/pmims_api/version.ts": $pmims_api_version,
    "./routes/time.ts": $time,
    "./routes/version.ts": $version,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
